# Generated by Django 2.1.5 on 2019-03-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
