# Generated by Django 2.1.5 on 2019-03-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=500)),
                ('comment_descr', models.TextField(null=True)),
                ('rating', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
