# Generated by Django 2.1.5 on 2019-03-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default='', max_length=7),
        ),
    ]
