# Generated by Django 2.1.5 on 2019-03-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190303_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='computing_id',
        ),
    ]
