# Generated by Django 2.1.5 on 2019-03-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190303_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
