# Generated by Django 2.1.7 on 2019-03-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20190303_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='', max_length=10)),
                ('Activity', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_10',
            field=models.ManyToManyField(related_name='Hour_10', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_11',
            field=models.ManyToManyField(related_name='Hour_11', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_12',
            field=models.ManyToManyField(related_name='Hour_12', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_13',
            field=models.ManyToManyField(related_name='Hour_13', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_14',
            field=models.ManyToManyField(related_name='Hour_14', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_15',
            field=models.ManyToManyField(related_name='Hour_15', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_16',
            field=models.ManyToManyField(related_name='Hour_16', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_17',
            field=models.ManyToManyField(related_name='Hour_17', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_18',
            field=models.ManyToManyField(related_name='Hour_18', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_19',
            field=models.ManyToManyField(related_name='Hour_19', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_20',
            field=models.ManyToManyField(related_name='Hour_20', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_21',
            field=models.ManyToManyField(related_name='Hour_21', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_22',
            field=models.ManyToManyField(related_name='Hour_22', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_23',
            field=models.ManyToManyField(related_name='Hour_23', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_24',
            field=models.ManyToManyField(related_name='Hour_24', to='login.Hour'),
        ),
        migrations.AddField(
            model_name='day',
            name='Hour_9',
            field=models.ManyToManyField(related_name='Hour_9', to='login.Hour'),
        ),
    ]
