# Generated by Django 2.1.7 on 2019-03-18 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190304_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(help_text='Ex. CS', max_length=4)),
                ('number', models.PositiveSmallIntegerField(help_text='Ex. 3240', validators=[django.core.validators.MaxValueValidator(9999)])),
                ('title', models.CharField(help_text='Ex. Adv. Software Development Methods', max_length=100)),
            ],
        ),
    ]
