# Generated by Django 2.1.5 on 2019-03-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190304_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(null=True),
        ),
    ]
