# Generated by Django 2.1.5 on 2019-03-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_profile_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_bio',
        ),
    ]
