# Generated by Django 2.1.7 on 2019-03-18 22:15

from django.db import migrations
from login.pull.parse import add_classes

def add_courses(apps, schema_editor):
    Course = apps.get_model('login', 'Course')
    add_classes(Course)


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_course'),
    ]

    operations = [
        migrations.RunPython(add_courses),
    ]
