# Generated by Django 2.1.7 on 2019-03-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20190318_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profiles',
            field=models.ManyToManyField(to='login.Profile'),
        ),
    ]
