# Generated by Django 2.1.7 on 2019-03-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_course_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('mnemonic', 'number')},
        ),
        migrations.RemoveField(
            model_name='course',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(to='login.Course'),
        ),
    ]
