# Generated by Django 2.1.5 on 2019-03-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_remove_profile_user_bio'),
        ('login', '0017_auto_20190319_0212'),
    ]

    operations = [
    ]
