# Generated by Django 2.1.5 on 2019-04-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computing_id', models.CharField(default='', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='people_who_I_like',
            field=models.ManyToManyField(related_name='people_who_I_like', to='login.Identifier'),
        ),
        migrations.AddField(
            model_name='profile',
            name='people_who_like_me',
            field=models.ManyToManyField(related_name='people_who_like_me', to='login.Identifier'),
        ),
    ]
