# Generated by Django 2.1.5 on 2019-04-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20190401_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='computing_id',
            field=models.TextField(null=True),
        ),
    ]
