# Generated by Django 2.1.7 on 2019-04-01 21:21

from django.db import migrations

day_to_str = [
    'Sun',
    'Mon',
    'Tue',
    'Wed',
    'Thu',
    'Fri',
    'Sat',
]

hour_to_str = [
    '12 AM',
    '1 AM',
    '2 AM',
    '3 AM',
    '4 AM',
    '5 AM',
    '6 AM',
    '7 AM',
    '8 AM',
    '9 AM',
    '10 AM',
    '11 AM',
    '12 PM',
    '1 PM',
    '2 PM',
    '3 PM',
    '4 PM',
    '5 PM',
    '6 PM',
    '7 PM',
    '8 PM',
    '9 PM',
    '10 PM',
    '11 PM',
]

def add_all_hours(apps, schema_editor):
    Hour = apps.get_model('login', 'Hour')

    for d in range(7):
        for hr in range(24):
            Hour.objects.get_or_create(day=d, hour=hr, display_text='{} {}'.format(day_to_str[d], hour_to_str[hr]))

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20190401_2120'),
    ]

    operations = [
        migrations.RunPython(add_all_hours),
    ]
