# Generated by Django 2.1.7 on 2019-04-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20190401_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hour',
            options={'ordering': ('day', 'hour')},
        ),
    ]
