# Generated by Django 2.1.5 on 2019-04-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_add-hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identifier',
            old_name='computing_id',
            new_name='liked',
        ),
        migrations.AddField(
            model_name='identifier',
            name='liker',
            field=models.TextField(null=True),
        ),
    ]
