# Generated by Django 2.1.7 on 2019-04-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_add-hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, default='', upload_to='documents/'),
        ),
    ]
