# Generated by Django 2.1.5 on 2019-04-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20190414_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identifier',
            old_name='computing_id1',
            new_name='computing_id',
        ),
    ]
