# Generated by Django 2.1.5 on 2019-04-24 14:26

from django.db import migrations

def remove_blank_profiles(apps, schema_editor):
    Profile = apps.get_model('login', 'Profile')
    for profile in Profile.objects.filter(first_name='', last_name=''):
        profile.user.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20190414_1636'),
    ]

    operations = [
        migrations.RunPython(remove_blank_profiles)
    ]
